### ISSUE TITLE
no attribute 'certbot_httpreq:installer_certbot_httpreq_config'

### ISSUE THREAD

**Issue by berkutta** [decryptus/certbot-httpreq#1]
Hi,

Not sure if I did something wrong but I don't get past the following error message:
```
➜  ~ sudo certbot \                                
  --agree-tos \
  --text \
  -a certbot-httpreq:auth \
  run
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
AttributeError: 'Namespace' object has no attribute 'certbot_httpreq:installer_certbot_httpreq_config'
Please see the logfiles in /var/log/letsencrypt for more details.
```

I created the config file under `/etc/letsencrypt/certbot-httpreq.yml` as described in the readme. I have used it on Archlinux and installed it with `sudo pip install certbot-httpreq certbot`.

**Comment by berkutta** [comment]
Getting the same no attribute error on a Debian 10.2 installation.

**Comment by decryptus** [comment]
Hi;

Could you give certbot version, please.

**Comment by berkutta** [comment]
Sure

Archlinux:
```
➜  ~ certbot --version
certbot 1.0.0
```

Debian:
```
$ certbot --version
certbot 0.39.0
```

**Comment by decryptus** [comment]
Could you check certbot-httpreq version 0.0.14
`pip install certbot-httpreq==0.0.14`

**Comment by berkutta** [comment]
Thanks, that was the issue! Not sure if this can be closed or if there will be a patch to fix this automatically.

**Comment by decryptus** [comment]
I renamed an argument but I forgot to rename it everywhere.
You can install the last version 0.0.15.
Thanks for the report.

Best regards.
