### ISSUE TITLE
Custom JSON Payload

### ISSUE THREAD

**Issue by guilherme-infomentum** [decryptus/certbot-httpreq#2]
Hi @decryptus,

Is there any option to use a custom JSON payload with the installer, or will it always use the following JSON payload?

`{"domain":"...","cert":"...","key":"...","chain":"..."}`

**Comment by decryptus** [comment]
Hi @guilherme-infomentum,

Could you explain me, why you need to custom payload and could you show me an example?

Best regards.

**Comment by decryptus** [comment]
Hi @guilherme-infomentum 

Maybe the last release should help you, I hope.

Best regards.

**Comment by decryptus** [comment]
Hi, @guilherme-infomentum, I haven't feedback from you, so I close the issue.

Best regards.
